### ISSUE TITLE
Document preview failing with 'NullPointerException: uri.host'

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/w3act#189]
When viewing a title from http://www.webarchive.org.uk/act-ddhapt-dev/documents/list, the preview fails reporting:
```
An unexpected error has occurred.
    Execution exception[[NullPointerException: uri.host]]
```
The log captures:
```
! @6k3bfib2m - Internal server error, for (GET) [/act-ddhapt-dev/site/http://www.ifs.org.uk/publications/feed/bn/] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: uri.host]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.5.jar:2.3.5]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.5.jar:2.3.5]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [com.typesafe.play.play_2.11-2.3.5.jar:2.3.5]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [com.typesafe.play.play_2.11-2.3.5.jar:2.3.5]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [org.scala-lang.scala-library-2.11.2.jar:na]
        at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:215) [org.scala-lang.scala-library-2.11.2.jar:na]
        at scala.util.Try$.apply(Try.scala:191) [org.scala-lang.scala-library-2.11.2.jar:na]
        at scala.util.Failure.recover(Try.scala:215) [org.scala-lang.scala-library-2.11.2.jar:na]
        at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [org.scala-lang.scala-library-2.11.2.jar:na]
        at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [org.scala-lang.scala-library-2.11.2.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.2.jar:na]
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.11-2.3.5.jar:2.3.5]
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.11.2.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.11.2.jar:na]
        at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.11.2.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.11.2.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.11.2.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.11-2.3.4.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.11-2.3.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.2.jar:na]
Caused by: java.lang.NullPointerException: uri.host
        at com.ning.http.client.RequestBuilderBase.setURI(RequestBuilderBase.java:385) ~[com.ning.async-http-client-1.8.14.jar:na]
        at com.ning.http.client.RequestBuilderBase.setUrl(RequestBuilderBase.java:380) ~[com.ning.async-http-client-1.8.14.jar:na]
        at com.ning.http.client.RequestBuilder.setUrl(RequestBuilder.java:155) ~[com.ning.async-http-client-1.8.14.jar:na]
        at play.api.libs.ws.ning.NingWSRequestHolder.createBuilder(NingWS.scala:429) ~[com.typesafe.play.play-ws_2.11-2.3.5.jar:2.3.5]
        at play.api.libs.ws.ning.NingWSRequestHolder.prepare(NingWS.scala:413) ~[com.typesafe.play.play-ws_2.11-2.3.5.jar:2.3.5]
        at play.api.libs.ws.ning.NingWSRequestHolder.execute(NingWS.scala:405) ~[com.typesafe.play.play-ws_2.11-2.3.5.jar:2.3.5]
        at play.api.libs.ws.WSRequestHolder$class.get(WS.scala:485) ~[com.typesafe.play.play-ws_2.11-2.3.5.jar:2.3.5]
        at play.api.libs.ws.ning.NingWSRequestHolder.get(NingWS.scala:361) ~[com.typesafe.play.play-ws_2.11-2.3.5.jar:2.3.5]
        at controllers.Helper$$anonfun$passthrough$1.apply(Helper.scala:14) ~[w3act.w3act-1.0.jar:1.0]
        at controllers.Helper$$anonfun$passthrough$1.apply(Helper.scala:14) ~[w3act.w3act-1.0.jar:1.0]
        at play.api.mvc.ActionBuilder$$anonfun$async$1.apply(Action.scala:481) ~[com.typesafe.play.play_2.11-2.3.5.jar:2.3.5]
        at play.api.mvc.ActionBuilder$$anonfun$async$1.apply(Action.scala:481) ~[com.typesafe.play.play_2.11-2.3.5.jar:2.3.5]
        at play.api.mvc.Action$.invokeBlock(Action.scala:556) ~[com.typesafe.play.play_2.11-2.3.5.jar:2.3.5]
        at play.api.mvc.Action$.invokeBlock(Action.scala:555) ~[com.typesafe.play.play_2.11-2.3.5.jar:2.3.5]
        at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518) ~[com.typesafe.play.play_2.11-2.3.5.jar:2.3.5]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.11-2.3.5.jar:2.3.5]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.11-2.3.5.jar:2.3.5]
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.11-2.3.5.jar:2.3.5]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.11-2.3.5.jar:2.3.5]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[com.typesafe.play.play_2.11-2.3.5.jar:2.3.5]
        at scala.Option.map(Option.scala:145) ~[org.scala-lang.scala-library-2.11.2.jar:na]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[com.typesafe.play.play_2.11-2.3.5.jar:2.3.5]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[com.typesafe.play.play_2.11-2.3.5.jar:2.3.5]
        at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705) ~[com.typesafe.play.play-iteratees_2.11-2.3.5.jar:2.3.5]
        at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705) ~[com.typesafe.play.play-iteratees_2.11-2.3.5.jar:2.3.5]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.11.2.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.11.2.jar:na]
        ... 6 common frames omitted

```

**Comment by anjackson** [comment]
Pretty sure this is resolved, since I've re-engineered this whole feature and it's currently in user testing, and these errors are not being reported. Closing.
