### ISSUE TITLE
Login issue for archivist@bl...

### ISSUE THREAD

**Issue by peterwebster** [ukwa/w3act#243]
User, Expert accounts both OK. When logging in with this account, I get in:

Execution exception[[RuntimeException: java.lang.reflect.InvocationTargetException]]

It may be that I have managed to create a new user account with the same email address - which suggests there should be some validation at that point.

**Comment by peterwebster** [comment]
Feel free to delete New Curator if need be @kinmanli

**Comment by peterwebster** [comment]
So, I logged in as administrator, and can see nothing wrong with the archivist account; have reset the password, no joy  @kinmanli

**Comment by peterwebster** [comment]
Admin unable to delete the account New Curator, as it is referenced by another object. It was just after creating this account that the issue arose.

**Comment by kinmanli** [comment]
added @ManyToMany(cascade = CascadeType.ALL) to User.roles so when you delete user it will delete the association

**Comment by kinmanli** [comment]
@peterwebster I'm unable to delete it as I don't have access to the "Live Server". I've added the fix to delete it properly via the UI and also will add validation for email check.

**Comment by kinmanli** [comment]
@peterwebster user email validation checked in https://github.com/ukwa/w3act/commit/2b95b0bc7b61941d055bc9441f7b5ba92294b048

**Comment by GilHoggarth** [comment]
Seeing the same original issue - unable to log in as archivist and seeing a Java error:
`Execution exception[[RuntimeException: java.lang.reflect.InvocationTargetException]]`

I've just redeployed the code (last few minutes) but wonder if i should redeploy and pull in Andy's act data - would that clear this issue?

**Comment by kinmanli** [comment]
Hi @GilHoggarth, I've checked the users using the UI and can't see any duplicate emails. What does the log say when logging in as archivist@bl.uk?

**Comment by GilHoggarth** [comment]
```
2015-01-29 10:53:58,856 - [ERROR] - from play in play-internal-execution-context-1
Cannot invoke the action, eventually got an error: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

2015-01-29 10:53:58,863 - [ERROR] - from application in play-internal-execution-context-1


! @6l2ng17ma - Internal server error, for (POST) [/actdev/login] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: java.lang.reflect.InvocationTargetException]]
        at play.api.Application$class.handleError(Application.scala:293) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.api.DefaultApplication.handleError(Application.scala:399) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.2.jar:na]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:257) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:411) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:408) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29) [org.scala-lang.scala-library-2.10.2.jar:na]
        at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [com.typesafe.play.play-iteratees_2.10-2.2.1.jar:2.2.1]
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:37) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:133) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:58) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:254) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:249) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.2.jar:na]
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at play.data.Form.bind(Form.java:391) ~[com.typesafe.play.play-java_2.10-2.2.1.jar:2.2.1]
        at play.data.Form.bindFromRequest(Form.java:215) ~[com.typesafe.play.play-java_2.10-2.2.1.jar:2.2.1]
        at controllers.ApplicationController.authenticate(ApplicationController.java:78) ~[w3act.w3act-1.0.jar:1.0]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$3$$anonfun$apply$3.apply(routes_routing.scala:1065) ~[w3act.w3act-1.0.jar:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$3$$anonfun$apply$3.apply(routes_routing.scala:1065) ~[w3act.w3act-1.0.jar:na]
        at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.GlobalSettings$1.call(GlobalSettings.java:64) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:278) ~[org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:274) ~[org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29) [org.scala-lang.scala-library-2.10.2.jar:na]
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[com.typesafe.akka.akka-actor_2.10-2.2.0.jar:2.2.0]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[com.typesafe.akka.akka-actor_2.10-2.2.0.jar:2.2.0]
        ... 4 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_45]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_45]
        at play.data.Form.bind(Form.java:388) ~[com.typesafe.play.play-java_2.10-2.2.1.jar:2.2.1]
        ... 22 common frames omitted
Caused by: javax.persistence.PersistenceException: Unique expecting 0 or 1 rows but got [2]
        at com.avaje.ebeaninternal.server.core.DefaultServer.findUnique(DefaultServer.java:1236) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
        at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findUnique(DefaultOrmQuery.java:903) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
        at com.avaje.ebeaninternal.util.DefaultExpressionList.findUnique(DefaultExpressionList.java:193) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
        at models.User.findByEmail(User.java:268) ~[w3act.w3act-1.0.jar:1.0]
        at controllers.ApplicationController$Login.validate(ApplicationController.java:44) ~[w3act.w3act-1.0.jar:1.0]
        ... 27 common frames omitted
```

**Comment by kinmanli** [comment]
@GilHoggarth that means there are 2 users with email 'archivist@bl.uk'. I've just checked via the UI and can't seem to find it.

Can you query the 'prod' db with select * from creator where email = 'archivist@bl.uk'; ?

Thanks

**Comment by GilHoggarth** [comment]
There are indeed two archivist creators. @peterwebster Okay for me to delete the 'New Curator' archivist?

**Comment by kinmanli** [comment]
@GilHoggarth how many users are you seeing in the DB? I'm seeing 49?

**Comment by GilHoggarth** [comment]
Yep, `count(*) from creator` = 49.

**Comment by kinmanli** [comment]
what's the ID of "New Curator"?

**Comment by GilHoggarth** [comment]
Does this means that the new archivist was once another user, and thus shouldn't be deleted; instead it should be edited back to whatever it was?

**Comment by kinmanli** [comment]
@GilHoggarth I'm sure I deleted the "New Curator" user this morning. It was 50, now 49.

**Comment by GilHoggarth** [comment]
id = 61; url blank; created_at blank

**Comment by GilHoggarth** [comment]
Okay, so it should just be deleted. @peterwebster Can you confirm that it's okay to delete this account - i.e., you're not specifically trying to check something with it that would be lost if I deleted this account.

**Comment by kinmanli** [comment]
what's the password for archivist@bl.uk?

**Comment by GilHoggarth** [comment]
Same as usual, in files.

**Comment by kinmanli** [comment]
@peterwebster try again with archivist@bl.uk

**Comment by peterwebster** [comment]
@GilHoggarth it was fine to delete New Curator.

Login now fine. @kinmanli 

We ended up with two curators with the same email because, while I was creating New Curator to test something, my browser autocompleted the field with the address I was logged in as (archivist@...) - AND I was then able to save it.
So, we probably need some validation there, but (at this stage in the project) it isn't critical before we go into production. So: leaving the ticket open, but with a low priority.

**Comment by GilHoggarth** [comment]
Good to know as I didn't actually delete New Curator - somewhere in the process it's been removed!

**Comment by kinmanli** [comment]
@peterwebster @gilhoggarth I removed the "New Curator" user as you specified above.

@peterwebster I've already added the email checked yesterday.

**Comment by peterwebster** [comment]
So you have @kinmanli !  Could you just amend the error message to read:

'There is already a user account with that email address. Please check and enter a different email address.'

Then we're done.

**Comment by kinmanli** [comment]
Fixed

**Comment by peterwebster** [comment]
Magic @kinmanli . Closing ticket now.
