### ISSUE TITLE
Internal server error - occasionally occuring for w3act target exports

### ISSUE THREAD

**Issue by GilHoggarth** [ukwa/w3act#282]
Spotted the following in the w3act log - Roger confirmed this is a bug that need addressing asap.
```
2015-03-03 13:26:12,968 - [ERROR] - from play in play-internal-execution-context-2
Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: org.postgresql.util.PSQLException: This connection has been closed.

2015-03-03 13:26:12,973 - [ERROR] - from application in play-internal-execution-context-2


! @6lc49858l - Internal server error, for (GET) [/act/targets/export/ld/weekly] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: org.postgresql.util.PSQLException: This connection has been closed.]]
        at play.api.Application$class.handleError(Application.scala:293) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.api.DefaultApplication.handleError(Application.scala:399) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.2.jar:na]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:257) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:411) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:408) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29) [org.scala-lang.scala-library-2.10.2.jar:na]
        at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [com.typesafe.play.play-iteratees_2.10-2.2.1.jar:2.2.1]
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:37) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:133) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:58) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:254) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:249) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.2.jar:na]
Caused by: javax.persistence.PersistenceException: org.postgresql.util.PSQLException: This connection has been closed.
        at com.avaje.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:339) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
        at com.avaje.ebeaninternal.server.core.DefaultServer.createQueryTransaction(DefaultServer.java:2018) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
        at com.avaje.ebeaninternal.server.core.OrmQueryRequest.initTransIfRequired(OrmQueryRequest.java:178) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
        at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1459) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
        at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:885) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
        at com.avaje.ebeaninternal.util.DefaultExpressionList.findList(DefaultExpressionList.java:177) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
        at models.LookupEntry.filterByName(LookupEntry.java:136) ~[w3act.w3act-1.0.jar:1.0]
        at uk.bl.scope.Scope.checkScopeIp(Scope.java:385) ~[w3act.w3act-1.0.jar:1.0]
        at models.Target.isInScope(Target.java:1340) ~[w3act.w3act-1.0.jar:1.0]
        at models.Target.exportLdFrequency(Target.java:1387) ~[w3act.w3act-1.0.jar:1.0]
        at controllers.TargetController.exportLdFrequencyJson(TargetController.java:821) ~[w3act.w3act-1.0.jar:1.0]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$156$$anonfun$apply$156.apply(routes_routing.scala:2317) ~[w3act.w3act-1.0.jar:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$156$$anonfun$apply$156.apply(routes_routing.scala:2317) ~[w3act.w3act-1.0.jar:na]
        at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.Router$Routes$$anon$1.invocation(Router.scala:377) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.GlobalSettings$1.call(GlobalSettings.java:64) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.mvc.Security$AuthenticatedAction.call(Security.java:45) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:278) ~[org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:274) ~[org.scala-lang.scala-library-2.10.2.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29) [org.scala-lang.scala-library-2.10.2.jar:na]
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) ~[com.typesafe.akka.akka-actor_2.10-2.2.0.jar:2.2.0]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) ~[com.typesafe.akka.akka-actor_2.10-2.2.0.jar:2.2.0]
        ... 4 common frames omitted
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
        at org.postgresql.jdbc2.AbstractJdbc2Connection.checkClosed(AbstractJdbc2Connection.java:714) ~[postgresql.postgresql-9.1-901-1.jdbc4.jar:na]
        at org.postgresql.jdbc2.AbstractJdbc2Connection.setAutoCommit(AbstractJdbc2Connection.java:661) ~[postgresql.postgresql-9.1-901-1.jdbc4.jar:na]
        at com.jolbox.bonecp.ConnectionHandle.setAutoCommit(ConnectionHandle.java:1292) ~[com.jolbox.bonecp-0.8.0.RELEASE.jar:na]
        at play.api.db.BoneCPApi$$anon$1.onCheckOut(DB.scala:329) ~[com.typesafe.play.play-jdbc_2.10-2.2.1.jar:2.2.1]
        at com.jolbox.bonecp.AbstractConnectionStrategy.postConnection(AbstractConnectionStrategy.java:75) ~[com.jolbox.bonecp-0.8.0.RELEASE.jar:na]
        at com.jolbox.bonecp.AbstractConnectionStrategy.getConnection(AbstractConnectionStrategy.java:92) ~[com.jolbox.bonecp-0.8.0.RELEASE.jar:na]
        at com.jolbox.bonecp.BoneCP.getConnection(BoneCP.java:553) ~[com.jolbox.bonecp-0.8.0.RELEASE.jar:na]
        at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:131) ~[com.jolbox.bonecp-0.8.0.RELEASE.jar:na]
        at play.db.ebean.EbeanPlugin$WrappingDatasource.getConnection(EbeanPlugin.java:147) ~[com.typesafe.play.play-java-ebean_2.10-2.2.1.jar:2.2.1]
        at com.avaje.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:313) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
        ... 31 common frames omitted
```

**Comment by kinmanli** [comment]
@PsypherPunk does this also happen on actdev?

**Comment by GilHoggarth** [comment]
@kinmanli Haven't seen this in the /actdev logs. I think it's triggered by an export request, which I think is only run on w3act - true @PsypherPunk ?

**Comment by PsypherPunk** [comment]
Yes, I haven't run exports against /actdev. It doesn't happen regularly though; it didn't occur yesterday, it happened several times in the small hours this morning and again a few minutes ago.

**Comment by kinmanli** [comment]
@PsypherPunk just want to see if it's a config or code issue. So would be good to make it fail on actdev

**Comment by kinmanli** [comment]
@PsypherPunk what is the criteria for the Targets you want exporting? It seems to be checking the geoip DB and if it's a UK, Scot, london etc

**Comment by PsypherPunk** [comment]
Yeah, it shouldn't be checking at that point. As long as the "no-LD-criteria-met" value is _false_ (and we can depend on that value being correct) then that should suffice.

**Comment by kinmanli** [comment]
@GilHoggarth checked in. Hopefully removing all that intense geo ip checking etc and just using the "noLDCriteriaMet" fixes it. Will need to see if the data is correct

**Comment by anjackson** [comment]
Can I assume that noLDCriteriaMet is always updated when the Scope is checked? e.g. on edit or import?

**Comment by GilHoggarth** [comment]
@PsypherPunk Code deployed onto /actdev

**Comment by kinmanli** [comment]
@anjackson, I will need to search for the ticket(s) regarding the noLDCriteriaMet. Last work was done was with validation.

For the caching are you talking about the "LookupEntry" table?

**Comment by anjackson** [comment]
No idea about how it might be implemented. I'd just assumed (perhaps naively) that the expensive checks would only be done 'on demand', but the results of those tests might be stored somewhere handy in the database so the last-known value could be checked. Maybe I'm wrong about all this?

**Comment by kinmanli** [comment]
Yes the ukhosting, ukregistration and top level domain checks are done on save.

**Comment by kinmanli** [comment]
@GilHoggarth fixed with an existing/same (tried & tested) method we used for the 'NPLD scope' tab.
Please redeploy to actdev or wait until the 5pm one.

@PsypherPunk please test when redeployed.

Thanks

**Comment by GilHoggarth** [comment]
Automated 5pm now scheduled at midnight (so not to interrupt like it did yesterday). Running redeploy now.

**Comment by GilHoggarth** [comment]
Upped the ulimit file handles to 409600 and user processes to 204800.

**Comment by GilHoggarth** [comment]
Roger to test.

**Comment by PsypherPunk** [comment]
Had this running on a loop for an hour without issue:

    #!/usr/bin/env python

    import json
    import requests

    response = requests.post("http://www.webarchive.org.uk/actdev/login", data={"email": "XXX", "password": "XXX"})
    cookie = response.history[0].headers["set-cookie"]
    headers = {
        "Cookie": cookie
    }

    frequencies = ["daily", "weekly", "monthly", "quarterly", "sixmonthly", "annual", "domaincrawl", "all"]
    while True:
        for frequency in frequencies:
            url = "http://www.webarchive.org.uk/actdev/targets/export/ld/%s" % frequency
            r = requests.get(url, headers=headers)
            j = json.loads(r.content)

**Comment by GilHoggarth** [comment]
Ran for a further 30 minutes on w3act - no issues. This really is an instance of a w3act service performance concern and as such should be considered in an on-going basis. So closing.
