### ISSUE TITLE
License links in view goes to the same place

### ISSUE THREAD

**Issue by kinmanli** [ukwa/w3act#318]
Clicking on a license link...

![screen shot 2015-03-21 at 21 02 36](https://cloud.githubusercontent.com/assets/1652105/6766820/bae1ccfa-d00d-11e4-82fc-cf0c814e4077.png)

... goes to the same view.

![screen shot 2015-03-21 at 21 04 11](https://cloud.githubusercontent.com/assets/1652105/6766827/ed90ce12-d00d-11e4-9588-0a653bef9bd7.png)

**Comment by kinmanli** [comment]
@nicolabingham @peterwebster are licenses editable/viewable individually?

**Comment by nicolabingham** [comment]
@kinmanli, yes they are.

**Comment by anjackson** [comment]
Okay, so, it turns out the system has only one license set up and hard-coded into the licence forms. Hence, it can't show a different form for the different cases. This should hopefully not be too difficult to change, although this depends on how radical the license form needs to change for each case.

**Comment by anjackson** [comment]
For 1.0.5, we'll ensure this is essentially working, but review again in the next release.

**Comment by GilHoggarth** [comment]
We’re now doing release testing on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.

**Comment by niladreeb** [comment]
Not working, rather it is giving NullPointerException

**Comment by anjackson** [comment]
From the server logs:
```
! @6mfef9iaa - Internal server error, for (GET) [/actstage/ukwa/license/view/133] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
        at play.api.Application$class.handleError(Application.scala:293) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.api.DefaultApplication.handleError(Application.scala:399) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.2.jar:na]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:261) [com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
Caused by: java.lang.NullPointerException: null
        at views.html.licence.ukwalicence$$anonfun$apply$1.apply(ukwalicence.template.scala:116) ~[w3act.w3act-1.0.jar:1.0]
        at views.html.licence.ukwalicence$$anonfun$apply$1.apply(ukwalicence.template.scala:77) ~[w3act.w3act-1.0.jar:1.0]
        at views.html.helper.form$.apply(form.template.scala:45) ~[com.typesafe.play.play_2.10-2.2.1.jar:2.2.1]
        at views.html.licence.ukwalicence$.apply(ukwalicence.template.scala:77) ~[w3act.w3act-1.0.jar:1.0]
        at views.html.licence.ukwalicence$.render(ukwalicence.template.scala:316) ~[w3act.w3act-1.0.jar:1.0]
        at views.html.licence.ukwalicence.render(ukwalicence.template.scala) ~[w3act.w3act-1.0.jar:1.0]
```

**Comment by anjackson** [comment]
Fixed and  on stage now.

**Comment by anjackson** [comment]
Can you take a look at this @nicolabingham ?

**Comment by nicolabingham** [comment]
@anjackson I checked this on /actstage. The different licence types are correctly reflected in the licence forms.

**Comment by niladreeb** [comment]
Tested in act and now different license templates are working correctly.
