### ISSUE TITLE
Upgrade jruby-whois to 3.5.9(.2)

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#358]
Improvements and bugfixes in the underlying library mean we should upgrade, and Do It Right (i.e. via Maven, and remove the old lib stuff and any CLI scripts.

Note that this also means moving the ```isUK``` logic out of the library and into here. See ukwa/jruby-whois#2

**Comment by GilHoggarth** [comment]
We’re now doing release testing on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.

**Comment by anjackson** [comment]
Try adding a 'www.marksandspencer.com' as a target (or updating existing target for that URL) and check the 'is UK registration' gets updated.

**Comment by niladreeb** [comment]
Tested with the url 'www.marksandspencer.com' both in actstage and actdev but its not updating the isUK registration to 'yes'.

**Comment by anjackson** [comment]
On the server side, we see:
```
2015-06-16 14:52:01,268 [^[[36mdebug^[[0m] application - after prefix: marksandspencer.com
2015-06-16 14:52:12,786 [^[[33mwarn^[[0m] application - whois lookup message: (Error) execution expired
org.jruby.embed.EvalFailedException: (Error) execution expired
        at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:132) ~[org.jruby.jruby-complete-1.7.20.jar:na]
        at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1341) ~[org.jruby.jruby-complete-1.7.20.jar:na]
        at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1372) ~[org.jruby.jruby-complete-1.7.20.jar:na]
        at uk.bl.wa.whois.JRubyWhois.lookup(JRubyWhois.java:64) ~[uk.bl.wa.whois.jruby-whois-3.5.9.2.jar:na]
        at uk.bl.wa.whois.JRubyWhois.lookup(JRubyWhois.java:48) ~[uk.bl.wa.whois.jruby-whois-3.5.9.2.jar:na]
        at uk.bl.scope.Scope.checkWhois(Scope.java:327) [w3act.w3act-1.0.jar:1.0]
org.jruby.exceptions.RaiseException: (Error) execution expired
```

So it looks like the whois lookups are timing out, presumably due to network restrictions.

**Comment by anjackson** [comment]
Any joy on the network/firewall issue?

**Comment by GilHoggarth** [comment]
I suspect whois requests are blocked going outwards of our 192.168.45 network, so have submitted a servicedesk call to get this changed.

**Comment by GilHoggarth** [comment]
Have raised this request with Steph as a matter of urgency, but equally it may not be completed today. @anjackson could this ticket be skipped for this release or does it provide a critical service key for v1.0.5?

**Comment by anjackson** [comment]
Not critical.

**Comment by GilHoggarth** [comment]
Closing as jruby-whois installed. Next milestone will need to test this.

**Comment by GilHoggarth** [comment]
Closing.
