### ISSUE TITLE
Tab 'Target creation' tab reports comes up with error

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#366]
After the 1.0.5 version was released the the tab 'Target creation' comes up with an error. It worked before the release:

https://www.webarchive.org.uk/act/reportscreation/targets/?s=createdAt&o=desc&curator=-1&organisation=-1&tld=either 

An unexpected error has occurred.

    Execution exception[[NoSuchElementException: null]]

       java.util.NoSuchElementException
       	at java.util.ArrayList$Itr.next(ArrayList.java:834)
       	at models.Target.pageReportsCreation(Target.java:1057)
       	at controllers.ReportController.targets(ReportController.java:341)
       	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$135$$anonfun$apply$135.apply(routes_routing.scala:2217)
       	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$135$$anonfun$apply$135.apply(routes_routing.scala:2217)
       	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183)
       	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377)
       	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56)
       	at play.GlobalSettings$1.call(GlobalSettings.java:64)
       	at play.mvc.Security$AuthenticatedAction.call(Security.java:45)
       	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91)
       	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90)
       	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)
       	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)
       	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:278)
       	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:274)
       	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29)
       	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37)
       	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
       	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
        [wrapped] @6mga340k8: Execution exception in null:null
       	at play.api.Application$class.handleError(Application.scala:293)
       	at play.api.DefaultApplication.handleError(Application.scala:399)
       	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261)
       	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261)
       	at scala.Option.map(Option.scala:145)
       	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:261)
       	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:257)
       	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
       	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:411)
       	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:408)
       	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29)
       	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43)
       	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:37)
       	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:133)
       	at scala.concurrent.Promise$class.complete(Promise.scala:55)
       	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:58)
       	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:254)
       	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:249)
       	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29)
       	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361)
       	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
       	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
       	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
       	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by GilHoggarth** [comment]
We’re now doing release testing of v1.0.6 on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.
Please remember to make it clear whether the ticket is successfully implemented or not.

**Comment by dorotawalker** [comment]
The tab 'Target creation' works fine.

**Comment by GilHoggarth** [comment]
We’re now doing release testing of v1.0.6 on live - https://www.webarchive.org.uk/act !
Please test that the implementation of this ticket works correctly on /act – if it does, please label this ticket as “3 - Done”, remove the “1 - Ready” label - and Close this ticket.
Please remember to make it clear whether the ticket is successfully implemented or not.

**Comment by nicolabingham** [comment]
Working fine now.
