### ISSUE TITLE
Unwanted change of the crawl frequency

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#373]
After hitting the save button in the 'Open License Request' the crawl frequency is changed to the Domain Crawl. The start date stays the same.

**Comment by dorotawalker** [comment]
The ticks in the NPLD Scope tab also disappear after saving in the 'Open Licenses'. The data in the fields remains the same.

**Comment by dorotawalker** [comment]
Happens with the new records and the edited ones.

**Comment by anjackson** [comment]
had you just edited the fields before hitting the Open License Request button, or had you pressed Save first?

**Comment by anjackson** [comment]
Okay, checked in 4d104b1d6c403a6745c0c0d095f19b229aa5628c which stripped out the default value settings, which appeared to be overwriting the DB settings in this case.

**Comment by GilHoggarth** [comment]
We’re now doing release testing of v1.0.6 on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.
Please remember to make it clear whether the ticket is successfully implemented or not.

**Comment by GilHoggarth** [comment]
Code fix failed. When attempting to add a new target, after clicking Save, the following Java error is displayed.


    Execution exception[[NullPointerException: null]]

       java.lang.NullPointerException
       	at controllers.TargetController.save(TargetController.java:1404)
       	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$173$$anonfun$apply$173.apply(routes_routing.scala:2525)
       	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$173$$anonfun$apply$173.apply(routes_routing.scala:2525)
       	at play.core.Router$HandlerInvoker$$anon$7$$anon$2.invocation(Router.scala:183)
       	at play.core.Router$Routes$$anon$1.invocation(Router.scala:377)
       	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:56)
       	at play.GlobalSettings$1.call(GlobalSettings.java:64)
       	at play.mvc.Security$AuthenticatedAction.call(Security.java:45)
       	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:91)
       	at play.core.j.JavaAction$$anon$3.apply(JavaAction.scala:90)
       	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)
       	at play.core.j.FPromiseHelper$$anonfun$flatMap$1.apply(FPromiseHelper.scala:82)
       	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:278)
       	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:274)
       	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29)
       	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:37)
       	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
       	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
        [wrapped] @6mjbfeefb: Execution exception in null:null
       	at play.api.Application$class.handleError(Application.scala:293)
       	at play.api.DefaultApplication.handleError(Application.scala:399)
       	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261)
       	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:261)
       	at scala.Option.map(Option.scala:145)
       	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:261)
       	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$2.applyOrElse(PlayDefaultUpstreamHandler.scala:257)
       	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
       	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:411)
       	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:408)
       	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29)
       	at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43)
       	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:37)
       	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:133)
       	at scala.concurrent.Promise$class.complete(Promise.scala:55)
       	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:58)
       	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:254)
       	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:249)
       	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29)
       	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361)
       	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
       	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
       	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
       	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by GilHoggarth** [comment]
Assigning to Andy for consideration of next action.

**Comment by PsypherPunk** [comment]
Just to check: are the new Targets actually being created despite the error?

**Comment by GilHoggarth** [comment]
I tried to create www.abc.co.uk, it failed, and browsing for it showed no result - https://www.webarchive.org.uk/actstage/targets/lookup?f=http%3A%2F%2Fwww.abc.co.uk

**Comment by anjackson** [comment]
Gah. Should be fixed in git now.

**Comment by dorotawalker** [comment]
I've tested two and they are not being added in ACT stage (http://yorkfestivalofideas.com/  and http://www.nationalcivilwarcentre.com/)

**Comment by dorotawalker** [comment]
Existing records ID 27328, 27108 and 27116 worked fine. The crawl frequency was not changed.

**Comment by GilHoggarth** [comment]
Still Java faults - https://www.webarchive.org.uk/actstage/targets/28226

**Comment by anjackson** [comment]
Okay, another try...

**Comment by GilHoggarth** [comment]
Tested again after new code release. Noted that previous attempt that Java faulted did still create the target record - deleted it to be tidy.
Successfully created new target; edited it and delete it. Working as I would expect. 
Issue passed.

**Comment by GilHoggarth** [comment]
We’re now doing release testing of v1.0.6 on live - https://www.webarchive.org.uk/act !
Please test that the implementation of this ticket works correctly on /act – if it does, please label this ticket as “3 - Done”, remove the “1 - Ready” label - and Close this ticket.
Please remember to make it clear whether the ticket is successfully implemented or not.

**Comment by nicolabingham** [comment]
Tested on live act, this has been fixed noe
