### ISSUE TITLE
Whois causing a hang on act-ddhapt

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#401]
Observing this on act-ddhapt:

```
"play-akka.actor.default-dispatcher-9090" prio=10 tid=0x00007fb89c509000 nid=0x825 runnable [0x00007fb8b1c9c000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.Throwable.fillInStackTrace(Native Method)
        at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
        - locked <0x00000007b8c73e80> (a java.lang.IndexOutOfBoundsException)
        at java.lang.Throwable.<init>(Throwable.java:265)
        at java.lang.Exception.<init>(Exception.java:66)
        at java.lang.RuntimeException.<init>(RuntimeException.java:62)
        at java.lang.IndexOutOfBoundsException.<init>(IndexOutOfBoundsException.java:56)
        at java.util.ArrayList.rangeCheck(ArrayList.java:635)
        at java.util.ArrayList.get(ArrayList.java:411)
        at org.jruby.embed.internal.BiVariableMap.getVariable(BiVariableMap.java:255)
        at org.jruby.embed.internal.BiVariableMap.put(BiVariableMap.java:316)
        at org.jruby.embed.internal.BiVariableMap.put(BiVariableMap.java:298)
        at org.jruby.embed.ScriptingContainer.put(ScriptingContainer.java:1124)
        at uk.bl.wa.whois.JRubyWhois.lookup(JRubyWhois.java:30)
        at uk.bl.scope.Scope.checkWhois(Scope.java:565)
        at uk.bl.scope.Scope.isUkRegistration(Scope.java:812)
        at models.Target.isUkRegistration(Target.java:1839)
        at views.html.targets.view$.apply(view.template.scala:225)
        at views.html.targets.view$.render(view.template.scala:1044)
        at views.html.targets.view.render(view.template.scala)
        at controllers.TargetController.view(TargetController.java:206)
```

From jstack, on a system that seems to be hanging. I think all the whois stuff should really be disabled at present, as it has never worked properly and will tend to lock up as whois requests are limited. 

This may be a difference between the deployed DDHAPT version and the current master.

**Comment by anjackson** [comment]
On restart, I'm seeing a bit of this old thing:

```
LoadError: no such file to load -- Whois
                 require at org/jruby/RubyKernel.java:1083
                 require at jar:file:/opt/w3act-1.0/lib/jruby-complete-1.7.9.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
                  (root) at jruby-whois.rb:2
                   apply at view.template.scala:614
```

Which is consistent with DDHAPT being out of date.

**Comment by anjackson** [comment]
This should get checked/resolved when we update DDHAPT, which Roman has agreed to help us with.

**Comment by GilHoggarth** [comment]
Andy, if you think this is relevant to milestone 1.1.0, please test this ticket. Otherwise reassign to a different milestone.

**Comment by anjackson** [comment]
This will be ready for @romankarl to help us with once we have a stable 1.1.0 release.

**Comment by anjackson** [comment]
Emailed @romankarl to see if he is able to help.

**Comment by GilHoggarth** [comment]
Closing as old ticket that seems to have become a non-issue.
