### ISSUE TITLE
On Editing targets having no owner gives NullPointerException

### ISSUE THREAD

**Issue by niladreeb** [ukwa/w3act#426]
![image](https://cloud.githubusercontent.com/assets/12607939/9271840/db9e4a20-4274-11e5-8ac9-e7e645c5443f.png)

**Comment by niladreeb** [comment]
Null check implemented.

**Comment by niladreeb** [comment]
Works fine in actstage.

**Comment by niladreeb** [comment]
Retested and acts fine.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Can't find any 'no owner' targets in postgres database, and can't create a target to test. So effectively untested and failed.

**Comment by GilHoggarth** [comment]
Failed.
Created new target - www.giltest.co.uk - then edited it as admin to set owner to None. Resulted in Execution exception[[NumberFormatException: For input string: ""]]

**Comment by GilHoggarth** [comment]
Still failing:
```
2015-09-03 15:17:50,948 [error] play - Cannot invoke the action, eventually got an error: java.lang.NumberFormatException: For input string: ""
2015-09-03 15:17:50,972 [error] application -

! @6nbggkfno - Internal server error, for (POST) [/actstage/targets/30128] ->

play.api.Application$$anon$1: Execution exception[[NumberFormatException: For input string: ""]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at scala.Option.map(Option.scala:146) [org.scala-lang.scala-library-2.11.7.jar:na]
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.7.0_65]
        at java.lang.Long.parseLong(Long.java:453) ~[na:1.7.0_65]
        at java.lang.Long.valueOf(Long.java:540) ~[na:1.7.0_65]
        at views.html.targets.edit$$anonfun$apply$3.apply(edit.template.scala:422) ~[w3act.w3act-1.1.0.jar:1.1.0]
        at views.html.targets.edit$$anonfun$apply$3.apply(edit.template.scala:278) ~[w3act.w3act-1.1.0.jar:1.1.0]
```

**Comment by niladreeb** [comment]
'--None--' option removed from Selector, which resolved the issue.

**Comment by GilHoggarth** [comment]
Good fix! Considered done on /actstage.

**Comment by GilHoggarth** [comment]
Andy, please test on /actstage.

**Comment by anjackson** [comment]
Can no longer set the user to 'None'. Passed.

**Comment by anjackson** [comment]
All good on production too.
