### ISSUE TITLE
Should not crash when a raw IP address is used

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#498]
A particular target (30173) crashes with:

~~~
java.lang.IllegalArgumentException: Not a valid domain name: '87.117.239.204'
   	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148)
   	at com.google.common.net.InternetDomainName.<init>(InternetDomainName.java:156)
   	at com.google.common.net.InternetDomainName.from(InternetDomainName.java:213)
   	at uk.bl.api.OverallLicenseStatus.getParentDomain(OverallLicenseStatus.java:178)
   	at uk.bl.api.OverallLicenseStatus.<init>(OverallLicenseStatus.java:88)
        ...
~~~

This should be caught and dealt with appropriately instead.

**Comment by anjackson** [comment]
Seems to be working on act-ddb

**Comment by GilHoggarth** [comment]
Issue not seen as problematic on https://www.webarchive.org.uk/actstage/targets/30173

**Comment by GilHoggarth** [comment]
Seen on live, closing.
