### ISSUE TITLE
NPE during playback of some resources

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#527]
Some resources lead to this:

~~~
! @70hl8oa2a - Internal server error, for (GET) [/act/wayback/20160613113704/http://www.guildford.gov.uk/guildford/fonts/OpenDyslexic-Bold.otf] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at scala.Option.map(Option.scala:146) [org.scala-lang.scala-library-2.11.7.jar:na]
Caused by: java.lang.NullPointerException: null
        at controllers.WaybackController.wayback(WaybackController.java:94) ~[w3act.w3act-1.2.0.jar:1.2.0]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$331$$anonfun$apply$331.apply(routes_routing.scala:5025) ~[w3act.w3act-1.2.0.jar:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$331$$anonfun$apply$331.apply(routes_routing.scala:5025) ~[w3act.w3act-1.2.0.jar:na]
        at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
~~~

i.e. [this code](https://github.com/ukwa/w3act/blob/w3act-v1.2.0/app/controllers/WaybackController.java#L94) assumes there is a ```Content-Type``` but this is not always the case. Code should be more robust and only pass on a ```Content-Type``` if there is one.

**Comment by GilHoggarth** [comment]
@anjackson Andy to test on /act-ddhapt.

**Comment by anjackson** [comment]
Tested on act-ddb - error no longer occurs in logs.

**Comment by anjackson** [comment]
Looks good on /act/
