### ISSUE TITLE
DB lock error on login

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#558]
Something is awry when logging in and attempting to update the last login time:

```
2016-10-14 18:17:53,414 [error] application -

! @71ld5dckl - Internal server error, for (POST) [/act-ddb/login] ->

play.api.Application$$anon$1: Execution exception[[OptimisticLockException: Data has changed. updated [0] rows sql[update creator set last_login=?, updated_at=? where id=? and updated_at=?] bind[null]]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at scala.Option.map(Option.scala:146) [org.scala-lang.scala-library-2.11.7.jar:na]
Caused by: javax.persistence.OptimisticLockException: Data has changed. updated [0] rows sql[update creator set last_login=?, updated_at=? where id=? and updated_at=?] bind[null]
        at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.checkRowCount(DmlHandler.java:95) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.persist.dml.UpdateHandler.execute(UpdateHandler.java:81) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:86) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.update(DmlBeanPersister.java:66) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeUpdateBean(DefaultPersistExecute.java:82) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
2016-10-14 18:18:37,277 [error] play - Cannot invoke the action, eventually got an error: javax.persistence.OptimisticLockException: Data has changed. updated [0] rows sql[update creator set last_login=?, updated_at=? where id=? and updated_at=?] bind[null]
```

Doesn't seem to be serious, but should be fixed if possible.

**Comment by chrispeacockbl** [comment]
@anjackson Did this only happen the once, or is it reproduceable? 
I can't see any way for this to happen unless someone was logged in as admin and happened to be updating the user in question - or - the same user was being used by someone else who was logging in or changing the password at the same time as the first person.

**Comment by anjackson** [comment]
That's strange. On production this error gets logged on every login! Hmm, maybe something else is going on. If you can't reproduce it when running against PostgreSQL we'll have to leave it, I think.

**Comment by chrispeacockbl** [comment]
Is there a trigger in the DB on Production only perhaps?

**Comment by anjackson** [comment]
Seems unlikely, as I tend to avoid putting logic in the DB, but it's possible. Would you be able to check?

**Comment by chrispeacockbl** [comment]
I don't currently have access to the Production DB I'm afraid (or maybe I do, but I don't know where to find it!).

**Comment by anjackson** [comment]
Ask @GilHoggarth!

**Comment by chrispeacockbl** [comment]
@GilHoggarth now asked!

**Comment by chrispeacockbl** [comment]
No, there aren't any triggers in the ddhapt database.

**Comment by chrispeacockbl** [comment]
...nor in Production.

**Comment by chrispeacockbl** [comment]
@anjackson What's the topology in act-ddb and Production, is the web server(s) load balanced?

**Comment by anjackson** [comment]
It's just one-to-one - there's no load balancing.
