### ISSUE TITLE
Exception when attempting to add new Target

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#564]
I'm running the latest tag (2.0.0-BETA-6) and it dies when attempting to add a new target!

e.g. https://dev.webarchive.org.uk/act/targets/new

```
   java.lang.NullPointerException
   	at scala.Predef$.Long2long(Predef.scala:358)
   	at views.html.targets.edit$$anonfun$apply$3.apply(edit.template.scala:1033)
   	at views.html.targets.edit$$anonfun$apply$3.apply(edit.template.scala:291)
   	at views.html.helper.form$.apply(form.template.scala:45)
   	at views.html.targets.edit$.apply(edit.template.scala:291)
   	at views.html.targets.edit$.render(edit.template.scala:1349)
   	at views.html.targets.edit.render(edit.template.scala)
   	at controllers.TargetController.newForm(TargetController.java:865)
   	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$207$$anonfun$apply$207.apply(routes_routing.scala:4054)
   	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$207$$anonfun$apply$207.apply(routes_routing.scala:4054)
   	at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264)
   	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255)
   	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55)
   	at play.GlobalSettings$1.call(GlobalSettings.java:67)
   	at play.mvc.Security$AuthenticatedAction.call(Security.java:44)
   	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
   	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
   	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
   	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
   	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
   	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)
   	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32)
   	at scala.concurrent.impl.Future$.apply(Future.scala:31)
   	at scala.concurrent.Future$.apply(Future.scala:492)
   	at play.core.j.JavaAction$class.apply(JavaAction.scala:82)
   	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252)
   	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
   	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
   	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
   	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
   	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
   	at scala.Option.map(Option.scala:145)
   	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
   	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
   	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
   	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
   	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
   	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
   	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
   	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
   	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
   	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    [wrapped] @72mmciom2: Execution exception in null:null
   	at play.api.Application$class.handleError(Application.scala:296)
   	at play.api.DefaultApplication.handleError(Application.scala:402)
   	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320)
   	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320)
   	at scala.Option.map(Option.scala:145)
   	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320)
   	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316)
   	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
   	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
   	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
   	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)
   	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
   	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
   	at scala.concurrent.Promise$class.complete(Promise.scala:55)
   	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
   	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23)
   	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
   	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
   	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
   	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
   	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
   	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by anjackson** [comment]
Line 1033 in the Scala version appears to be this one:

```
1033:                                    <a class="btn btn-success" href=""""),_display_(/*1002.71*/routes/*1002.77*/.LoginCredentialsController.edit(id)),format.raw/*1002.113*/("""">
```

So it looks like cutting and pasting the `LoginCredentialsController` into this page broke something.

**Comment by anjackson** [comment]
Okay, needed to cope when there's no ID yet.
