### ISSUE TITLE
Slow response for common actions

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#626]
A number of common actions are very slow, e.g. editing Targets. Can we speed it up somehow?

**Comment by anjackson** [comment]
@min2ha can you add any notes on what you've been doing on this here please?

**Comment by crarugal** [comment]
Would tweaking these runttime parameters would be of any benefit?

![Screenshot 2019-08-06 16 04 52](https://user-images.githubusercontent.com/18530934/62551615-3eb80b00-b864-11e9-83b4-6c5cecc84420.png)
[Postgres run-time paramters.xlsx](https://github.com/ukwa/w3act/files/3472902/Postgres.run-time.paramters.xlsx)

**Comment by anjackson** [comment]
I've been profiling the code locally looking for some performance issues.  I'm using editing target 1 (GOV.UK Publications) as an example to start with.

Opening the EDIT tab takes 40s on my (pretty quick) laptop.  Following some profiling and thread inspection, I added some timing code in a couple of places, and it appears to be spending

- 20-25s in `getCollectionsData` (!)
- 3-4s in `OverallLicenseStatus`, but this is being run four or five times!

Artificially chopping out the complex logic of `OverallLicenseStatus` got it down to 25-30s, so I think at least on of those calls corresponds to a follow-up request rather than the original page.

```
java.lang.Exception: FOR WHY
        at uk.bl.api.OverallLicenseStatus.<init>(OverallLicenseStatus.java:67)
        at models.Target.getOverallLicenseStatus(Target.java:2228)
        at models.Target.hasInheritedLicense(Target.java:2245)
        at models.Target.indicateLicenses(Target.java:2302)
        at uk.bl.api.FormHelper.hasGrantedLicense(FormHelper.java:40)
        at views.html.targets.edit$.apply(edit.template.scala:264)
        at views.html.targets.edit$.render(edit.template.scala:1368)
        at views.html.targets.edit.render(edit.template.scala)
        at controllers.TargetController.edit(TargetController.java:963)
```

```
ava.lang.Exception: FOR WHY
        at uk.bl.api.OverallLicenseStatus.<init>(OverallLicenseStatus.java:67)
        at models.Target.getOverallLicenseStatus(Target.java:2228)
        at uk.bl.api.FormHelper.licensingUnderway(FormHelper.java:67)
        at views.html.targets.edit$.apply(edit.template.scala:267)
        at views.html.targets.edit$.render(edit.template.scala:1368)
        at views.html.targets.edit.render(edit.template.scala)
        at controllers.TargetController.edit(TargetController.java:963)
```

```
ava.lang.Exception: FOR WHY
        at uk.bl.api.OverallLicenseStatus.<init>(OverallLicenseStatus.java:67)
        at models.Target.getOverallLicenseStatus(Target.java:2228)
        at models.Target.hasInheritedNpldScope(Target.java:2251)
        at models.Target.indicateNpldStatus(Target.java:2257)
        at uk.bl.api.FormHelper.indicateNpldStatus(FormHelper.java:47)
        at views.html.targets.edit$$anonfun$apply$3.apply(edit.template.scala:753)
        at views.html.targets.edit$$anonfun$apply$3.apply(edit.template.scala:293)
        at views.html.helper.form$.apply(form.template.scala:45)
        at views.html.targets.edit$.apply(edit.template.scala:293)
        at views.html.targets.edit$.render(edit.template.scala:1368)
        at views.html.targets.edit.render(edit.template.scala)
        at controllers.TargetController.edit(TargetController.java:963)
```

```
java.lang.Exception: FOR WHY
        at uk.bl.api.OverallLicenseStatus.<init>(OverallLicenseStatus.java:67)
        at models.Target.getOverallLicenseStatus(Target.java:2228)
        at uk.bl.api.FormHelper.inheritedLicenceUnderwayOrGranted(FormHelper.java:80)
        at views.html.targets.edit$$anonfun$apply$3.apply(edit.template.scala:1083)
        at views.html.targets.edit$$anonfun$apply$3.apply(edit.template.scala:293)
        at views.html.helper.form$.apply(form.template.scala:45)
        at views.html.targets.edit$.apply(edit.template.scala:293)
        at views.html.targets.edit$.render(edit.template.scala:1368)
        at views.html.targets.edit.render(edit.template.scala)
        at controllers.TargetController.edit(TargetController.java:963)
```

All four events appears to be part of the same request/response.

This likely means the initial license check result is not getting effectively cached between the object, form and templates. 

However, the 20s delay from `getCollectionsData` is the big one. If we artificially cut this out, the page response time goes down to 3-4s. Which is frankly still not that fast but at least might be acceptable.

So, we need to work out why `getCollectionsData` is slow, and either improve the DB config and code to be faster, or cache it more effectively.  We also need to avoid `OverallLicenseStatus` being called more than once.

**Comment by anjackson** [comment]
Looks like after the initial scan for top-level collections (~4s) the `getCollectionData` code spends most of it's time in `getCollectionTreeElements` which recursively grabs all the collections as a big JSON tree. 

Two options spring to mind.

First, we should probably cache this tree and update it in the background couple of minutes. This does mean the user sees a 'stale' copy sometimes, when the collections are being changed, but this is a small price to pay for a significant speed up.

Secondly, we could also look at avoiding this recursive tree of calls to PostgreSQL. The collections tree is really not that large, and it is highly likely more efficient to collect all the Collections in one pass, and re-arrange them into a tree in RAM rather than via `N` database connections.

**Comment by anjackson** [comment]
The very similar `getCollectionsDataByIds` call is involved in `Targets.list` and is likely contributing to the slowness there, but there may of course be other causes there. That said, locally I get a 23s delay on `Targets.list` of which 20s was `getCollectionsDataByIds`.
