### ISSUE TITLE
GeoIP DB not bundled right

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#648]
From production:

```
2020-03-11 12:31:39,202 [^[[33mwarn^[[0m] application - GeoIP error.
java.lang.NullPointerException: null
        at uk.bl.scope.Scope.queryDb(Scope.java:197) [w3act.w3act-2.3.0.jar:2.3.0]
        at uk.bl.scope.Scope.checkGeoIp(Scope.java:285) [w3act.w3act-2.3.0.jar:2.3.0]
        at uk.bl.scope.Scope.isUkHosting(Scope.java:410) [w3act.w3act-2.3.0.jar:2.3.0]
        at models.Target.runChecks(Target.java:2425) [w3act.w3act-2.3.0.jar:2.3.0]
        at controllers.TargetController.validateForm(TargetController.java:1677) [w3act.w3act-2.3.0.jar:2.3.0]
```

**Comment by anjackson** [comment]
Ah, okay, this change has caused #592 to come back and cause this issue too:

https://github.com/ukwa/w3act/commit/90c6b705138f60e708c70bded21487708eac20ef#diff-3254677a7917c6c01f55212f86c57fbf

The `Dockerfile` needs to set the `WORKDIR` to `/w3act` and the GeoIP database needs to be `COPY`d into that folder too (i.e. should end up at `/w3act/GeoLite2-City.mmdb`).
